NUMPY

In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.5'

In [4]:
my_list=[0,1,2,3,4,5]

In [5]:
my_list

[0, 1, 2, 3, 4, 5]

In [6]:
type(my_list)

list

In [7]:
arr=np.array(my_list)

In [8]:
arr

array([0, 1, 2, 3, 4, 5])

In [11]:
print(type(my_list))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [16]:
np.arange(10,50,5,4)

TypeError: Cannot interpret '4' as a data type

In [17]:
np.arange(20,10)

array([], dtype=int64)

In [18]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [19]:
np.zeros(3)          #parameter tuning

array([0., 0., 0.])

In [20]:
np.zeros(3,dtype=int)        #hyperparameter tuning

array([0, 0, 0])

In [21]:
np.zeros(3,dtype=float) 

array([0., 0., 0.])

In [23]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [24]:
np.zeros([10,10],dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [25]:
np.ones(4)

array([1., 1., 1., 1.])

In [26]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [27]:
np.two(3)

AttributeError: module 'numpy' has no attribute 'two'

In [28]:
np.rand(3)

AttributeError: module 'numpy' has no attribute 'rand'

In [29]:
np.random.rand(3)

array([0.07158038, 0.03442145, 0.28252227])

In [32]:
np.random.rand(3,4)

array([[0.61063985, 0.81094439, 0.16615504, 0.7182923 ],
       [0.96834858, 0.84482811, 0.07301721, 0.70256926],
       [0.06595285, 0.3721101 , 0.66603609, 0.11438653]])

In [38]:
np.random.randint(3)

2

In [36]:
np.random.randint(10,20)

13

In [41]:
np.random.randint(1,10,4)

array([2, 9, 6, 9], dtype=int32)

In [43]:
print(np.random.randint(1,10,4))

[6 9 7 6]


In [44]:
m=np.random.randint(10,40,(10,10))       #random integers between 10 to 40 in 10 rows and 10 columns

In [46]:
print(m)

[[13 32 30 38 17 23 23 16 30 24]
 [10 18 14 27 12 34 38 24 23 34]
 [21 33 24 27 26 21 12 28 14 33]
 [30 32 17 34 35 11 12 36 25 30]
 [22 12 36 12 22 33 36 29 32 22]
 [14 30 12 28 27 14 30 12 27 13]
 [24 20 31 37 32 23 35 26 31 23]
 [20 29 35 10 25 39 33 33 18 28]
 [32 25 20 18 36 17 33 14 31 20]
 [33 15 35 20 25 34 34 37 15 33]]


In [48]:
m=np.random.randint(1,10,(5,4))

In [49]:
print(m)

[[9 2 6 6]
 [3 6 3 5]
 [1 9 6 8]
 [8 1 7 2]
 [4 6 6 9]]


In [50]:
m=np.random.randint(1,10,(4,6))

In [51]:
print(m)

[[8 4 8 5 7 9]
 [7 9 9 8 7 6]
 [9 2 3 8 6 7]
 [5 9 6 2 1 9]]


In [52]:
m[0]

array([8, 4, 8, 5, 7, 9], dtype=int32)

In [53]:
print(m[0])

[8 4 8 5 7 9]


In [56]:
m[0]=[2,6,9,5,9,4]

In [57]:
print(m)

[[2 6 9 5 9 4]
 [7 9 9 8 7 6]
 [9 2 3 8 6 7]
 [5 9 6 2 1 9]]


In [58]:
m[2]

array([9, 2, 3, 8, 6, 7], dtype=int32)

In [59]:
print(m[2])

[9 2 3 8 6 7]


In [60]:
m[-3]

array([7, 9, 9, 8, 7, 6], dtype=int32)

In [61]:
m[0,4]

np.int32(9)

In [62]:
print(m[0,4])

9


In [63]:
print(m[1,3])

8


In [64]:
print(m[-2,-3])

8


In [65]:
m[:]

array([[2, 6, 9, 5, 9, 4],
       [7, 9, 9, 8, 7, 6],
       [9, 2, 3, 8, 6, 7],
       [5, 9, 6, 2, 1, 9]], dtype=int32)

In [68]:
m[:2]

array([[2, 6, 9, 5, 9, 4],
       [7, 9, 9, 8, 7, 6]], dtype=int32)

In [69]:
m[:3]

array([[2, 6, 9, 5, 9, 4],
       [7, 9, 9, 8, 7, 6],
       [9, 2, 3, 8, 6, 7]], dtype=int32)

In [70]:
m[:4]

array([[2, 6, 9, 5, 9, 4],
       [7, 9, 9, 8, 7, 6],
       [9, 2, 3, 8, 6, 7],
       [5, 9, 6, 2, 1, 9]], dtype=int32)

In [71]:
m[0:4]

array([[2, 6, 9, 5, 9, 4],
       [7, 9, 9, 8, 7, 6],
       [9, 2, 3, 8, 6, 7],
       [5, 9, 6, 2, 1, 9]], dtype=int32)

In [72]:
m[0:3]

array([[2, 6, 9, 5, 9, 4],
       [7, 9, 9, 8, 7, 6],
       [9, 2, 3, 8, 6, 7]], dtype=int32)

In [73]:
m[1:4]

array([[7, 9, 9, 8, 7, 6],
       [9, 2, 3, 8, 6, 7],
       [5, 9, 6, 2, 1, 9]], dtype=int32)

In [76]:
m[-1:5]

array([[5, 9, 6, 2, 1, 9]], dtype=int32)

In [77]:
print(m)

[[2 6 9 5 9 4]
 [7 9 9 8 7 6]
 [9 2 3 8 6 7]
 [5 9 6 2 1 9]]


In [79]:
m[::2]

array([[2, 6, 9, 5, 9, 4],
       [9, 2, 3, 8, 6, 7]], dtype=int32)

In [80]:
m[::3]

array([[2, 6, 9, 5, 9, 4],
       [5, 9, 6, 2, 1, 9]], dtype=int32)

In [81]:
m.max()

np.int32(9)

In [82]:
m.min()

np.int32(1)

In [83]:
m.mean()

np.float64(6.166666666666667)

In [84]:
m.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'