1. Array creation functions

In [ ]:
import numpy as np 

In [8]:
# Create an array from a list
a = np.array([1, 2, 3])
print("Array a:", a)

Array a: [1 2 3]


In [9]:
# Create an array with evenly spaced values
b = np.arange(0,10,3)
print("Array b:", b)

Array b: [0 3 6 9]


In [11]:
# Create an array filled with zeros
c=np.zeros((4,5))
print("Array c:\n", c)

Array c:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [12]:
# Create an array filled with zeros
d=np.zeros((4,5), dtype=int)
print("Array d:\n",d)

Array d:
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [13]:
# Create an array filled with ones
e=np.ones((4,5))
print ("Array e:\n", e)

Array e:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# Create an identity matrix
f=np.eye(4)
print("Identity matrix f:\n", f)

Identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# 2. Array Manipulation Functions

In [ ]:
# Reshape an array
a1=np.array([1,2,3])
reshaped=np.reshape(a1,(3,1))
print("Reshaped array:", reshaped)

Reshaped array: [[1]
 [2]
 [3]]


In [19]:
# Flatten an array
f1 = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11,12]])
flattened=np.ravel(f1)
print   ("Flattened array:", flattened)

Flattened array: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
# Transpose an array
e1=np.array([[1,2],[3,4],[5,6]])
transposed=np.transpose(e1)
print("Transposed array:\n", transposed)

Transposed array:
 [[1 3 5]
 [2 4 6]]


In [ ]:
# Stack arrays vertically
a2=np.array([2,3])
b2=np.array([4,5])
stacked=np.vstack((a2,b2))
print("Stacked arrays:\n", stacked)

Stacked arrays:
 [[2 3]
 [4 5]]


In [ ]:
# Stack arrays horizontal
a2=np.array([2,3])
b2=np.array([4,5])
stacked=np.hstack((a2,b2))
print("Stacked arrays:\n", stacked)

Stacked arrays:
 [2 3 4 5]


In [ ]:
# 3. Mathematical Functions

In [ ]:
# Add two arrays
g=np.array([1,2,3,4,5])
added=np.add(g,10)
print("Added 10 to each element:", added)

Added 10 to each element: [11 12 13 14 15]


In [ ]:
# Square each element
squared=np.power(g,2)
print("squared array:", squared)

squared array: [ 1  4  9 16 25]


In [27]:
sqrt_val=np.sqrt(g)
print("Square root of each g:", sqrt_val)

Square root of each g: [1.         1.41421356 1.73205081 2.         2.23606798]


In [28]:
print(a)
print(g)

[1 2 3]
[1 2 3 4 5]


In [29]:
a3=np.array([1,2,3])
dot_product=np.dot(a,g)
print("Dot product of a and g:", dot_product)

ValueError: shapes (3,) and (5,) not aligned: 3 (dim 0) != 5 (dim 0)

In [30]:
print(a)
print(a1)

[1 2 3]
[1 2 3]


In [31]:
a3=np.array([1,2,3])
dot_product=np.dot(a,a1)
print("Dot product of a and a1:", dot_product)

Dot product of a and a1: 14


In [ ]:
# 4. Statistical Functions

In [32]:
s=np.array([1,2,3,4,5])
mean=np.mean(s)
print("Mean of s:", mean)

Mean of s: 3.0


In [33]:
var=np.var(s)
print("Variance of s:", var)

Variance of s: 2.0


In [34]:
std_dev=np.std(s)
print("Standard deviation of s:", std_dev)

Standard deviation of s: 1.4142135623730951


In [35]:
s

array([1, 2, 3, 4, 5])

In [36]:
minimum=np.min(s)
print("Minimum of s:", minimum)

Minimum of s: 1


In [37]:
maximum=np.max(s)
print("Maximum of s:", maximum)

Maximum of s: 5


In [ ]:
# 5. Linear Algebra Functions

In [38]:
matrix = np.array([[1, 2], [3, 4]]) 
matrix

array([[1, 2],
       [3, 4]])

In [ ]:
# 6. Random Sampling Functions

In [50]:
random_values=np.random.rand(6)
print("Random values between 0 and 2:", random_values)

Random values between 0 and 2: [0.77815675 0.87001215 0.97861834 0.79915856 0.46147936 0.78052918]


In [56]:
np.random.seed(0)
random_values=np.random.rand(6)
print("Random values with seed:", random_values)

Random values with seed: [0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411]


In [59]:
rand_int=np.random.randint(1,10,size=8)
print("Random integers between 1 and 10:", rand_int)

Random integers between 1 and 10: [4 6 1 3 4 9 2 4]


In [63]:
np.random.seed(0)
random_values=np.random.randint(1,10,size=8)
print("Random integers with seed:", random_values)

Random integers with seed: [6 1 4 4 8 4 6 3]


In [ ]:
# 7. Boolean & Logical Functions

In [64]:
logical_test = np.array([True, False, True]) 
all_true = np.all(logical_test)
print("Are all values true?", all_true)

Are all values true? False


In [65]:
logical_test = np.array([True, True, True]) 
all_true = np.all(logical_test)
print("Are all values true?", all_true)

Are all values true? True


In [66]:
logical_test = np.array([False, False, False]) 
all_true = np.all(logical_test)
print("Are all values true?", all_true)

Are all values true? False


In [67]:
any_true = np.any(logical_test)
print("Is any value true?", any_true)

Is any value true? False


In [68]:
logical_test = np.array([True, False, False])
any_true = np.any(logical_test)
print("Is any value true?", any_true)

Is any value true? True


In [ ]:
# 8. Set Operations

In [69]:
set_a = np.array([1, 2, 3, 4, 5])
set_b = np.array([3, 4, 5, 6])
intersection = np.intersect1d(set_a, set_b)
print("Intersection of set_a and set_b:", intersection)

Intersection of set_a and set_b: [3 4 5]


In [72]:
union=np.union1d(set_a, set_b)
print("Union of set_a and set_b:", union)

Union of set_a and set_b: [1 2 3 4 5 6]


In [ ]:
# 9. Array Attribute Functions

In [73]:
a=np.array([[1,2,3],[4,5,6]])
shape=a.shape
size=a.size
dimensions=a.ndim
dtype=a.dtype

print("Shape of a:", shape)
print("Size of a:", size)
print("Dimensions of a:", dimensions)
print("Data type of a:", dtype)

Shape of a: (2, 3)
Size of a: 6
Dimensions of a: 2
Data type of a: int64


In [ ]:
# 10. Array Attribute Functions

In [83]:
a = np.array([1, 2, 3])
copied_array = np.copy(a)  # Create a copy of array a
print("Copied array:", copied_array)

Copied array: [1 2 3]


In [84]:
array_size_in_bytes = a.nbytes
print("Size of array a in bytes:", array_size_in_bytes)

Size of array a in bytes: 24


In [85]:
shared=np.shares_memory(a, copied_array)
print("Do a and copied_array share memory?", shared)

Do a and copied_array share memory? False
